In [8]:
import numpy as np

Creating arrays

In [9]:
zero_arrays=np.zeros(5)
zero_arrays

array([0., 0., 0., 0., 0.])

In [10]:
ones_array=np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [11]:
constant_array=np.full(5,2.5)
constant_array

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [12]:
range_array=np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
linspace_array=np.linspace(0,1,11)
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi-dimensional array

In [16]:
zeros_matrix = np.zeros((5, 2))
zeros_matrix


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
ones_matrix = np.ones((5, 2))
ones_matrix


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
constant_matrix = np.full((5, 2), 3)
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])